#!/bin/sh
#/etc/init.d/powerbot

case "$1" in
start)
echo "Starting powerbot..."
/opt/powerbot/run.py &
;;

stop)
echo "Stopping powerbot..."
killall run.py
;;

*)
echo "Usage: /etc/init.d/powerbot (start|stop)"
exit 1
;;

esac

exit 0
